# Generated by Django 4.2.11 on 2024-03-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiragana', models.CharField(max_length=500)),
                ('romaji', models.CharField(max_length=500)),
                ('translation', models.CharField(max_length=500)),
                ('kanji_sentence', models.CharField(max_length=500)),
            ],
        ),
    ]
