# Generated by Django 5.0.7 on 2024-08-02 02:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoreProcessing',
            new_name='CoreDataProcessing',
        ),
    ]
