# Generated by Django 5.0.7 on 2024-08-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0002_rename_coreprocessing_coredataprocessing'),
    ]

    operations = [
        migrations.AddField(
            model_name='coredataprocessing',
            name='character_type_counts',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='coredataprocessing',
            name='learned_kanji',
            field=models.CharField(blank=True, max_length=50000),
        ),
        migrations.AddField(
            model_name='coredataprocessing',
            name='learning_kanji',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='coredataprocessing',
            name='penalty_kanji',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='coredataprocessing',
            name='test_threshold',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='coredataprocessing',
            name='user_kanji_level',
            field=models.IntegerField(default=5),
        ),
    ]
