# Generated by Django 4.2.11 on 2024-04-03 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('type', '0002_userkanjidata_delete_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkanjidata',
            name='next_kanji',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userkanjidata',
            name='learned_kanji',
            field=models.CharField(blank=True, max_length=50000),
        ),
        migrations.AlterField(
            model_name='userkanjidata',
            name='learning_kanji',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='userkanjidata',
            name='revising_kanji',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userkanjidata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
