# Generated by Django 5.0.7 on 2024-08-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0003_coredataprocessing_character_type_counts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coredataprocessing',
            name='all_kanjis',
            field=models.CharField(blank=True, max_length=50000),
        ),
    ]
