# Generated by Django 4.2.11 on 2024-04-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0003_userkanjidata_next_kanji_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
