# Generated by Django 5.0.7 on 2024-08-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0004_coredataprocessing_all_kanjis'),
    ]

    operations = [
        migrations.AddField(
            model_name='coredataprocessing',
            name='penalty_char_counts',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='coredataprocessing',
            name='penalty_threshold',
            field=models.SmallIntegerField(default=5),
        ),
    ]
