# Generated by Django 4.2.11 on 2024-04-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0005_userkanjidata_character_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userkanjidata',
            old_name='character_stats',
            new_name='character_type_counts',
        ),
    ]
