# Generated by Django 5.0.7 on 2024-09-15 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0006_coredataprocessing_learning_sentence_counter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coredataprocessing',
            name='learned_kanji',
        ),
        migrations.RemoveField(
            model_name='coredataprocessing',
            name='learning_kanji',
        ),
        migrations.RemoveField(
            model_name='coredataprocessing',
            name='penalty_char_counts',
        ),
        migrations.RemoveField(
            model_name='coredataprocessing',
            name='penalty_kanji',
        ),
        migrations.RemoveField(
            model_name='coredataprocessing',
            name='penalty_threshold',
        ),
        migrations.RemoveField(
            model_name='coredataprocessing',
            name='test_threshold',
        ),
        migrations.AddField(
            model_name='coredataprocessing',
            name='current_kanji_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coredataprocessing',
            name='all_kanjis',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='KanjiCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=1)),
                ('card_state', models.JSONField(default=dict)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'kanji')},
            },
        ),
    ]
