# Generated by Django 4.2.11 on 2024-04-05 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0006_rename_character_stats_userkanjidata_character_type_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkanjidata',
            name='revising_kanji',
        ),
    ]
