# Generated by Django 4.2.11 on 2024-04-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0007_remove_userkanjidata_revising_kanji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkanjidata',
            name='next_kanji',
            field=models.CharField(blank=True, max_length=50000),
        ),
    ]
