# Generated by Django 5.0.7 on 2024-09-20 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0007_remove_coredataprocessing_learned_kanji_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='coredataprocessing',
            old_name='character_type_counts',
            new_name='char_type_counts',
        ),
        migrations.RemoveField(
            model_name='coredataprocessing',
            name='all_kanjis',
        ),
        migrations.RemoveField(
            model_name='coredataprocessing',
            name='current_kanji_index',
        ),
        migrations.RemoveField(
            model_name='coredataprocessing',
            name='learning_sentence_counter',
        ),
        migrations.RemoveField(
            model_name='coredataprocessing',
            name='test_sentence_counter',
        ),
        migrations.RemoveField(
            model_name='coredataprocessing',
            name='user_kanji_level',
        ),
        migrations.AddField(
            model_name='coredataprocessing',
            name='all_kanji',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='coredataprocessing',
            name='learned_kanji',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='coredataprocessing',
            name='temp_char_type_counts',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='coredataprocessing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='KanjiCard',
        ),
    ]
