# Generated by Django 4.2.11 on 2024-06-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0008_alter_userkanjidata_next_kanji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userkanjidata',
            old_name='next_kanji',
            new_name='perfected_kanji',
        ),
        migrations.AddField(
            model_name='userkanjidata',
            name='penalty_kanji',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='userkanjidata',
            name='user_kanji_level',
            field=models.IntegerField(default=5),
        ),
    ]
