# Generated by Django 5.0.7 on 2024-09-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0008_rename_character_type_counts_coredataprocessing_char_type_counts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coredataprocessing',
            name='all_kanji',
        ),
        migrations.AddField(
            model_name='coredataprocessing',
            name='kanji_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='coredataprocessing',
            name='known_kanji',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='coredataprocessing',
            name='learning_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='coredataprocessing',
            name='upcomming_kanji',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='coredataprocessing',
            name='learned_kanji',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
