# Generated by Django 4.2.11 on 2024-07-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0009_rename_next_kanji_userkanjidata_perfected_kanji_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkanjidata',
            name='perfected_kanji',
        ),
        migrations.AddField(
            model_name='userkanjidata',
            name='test_threshold',
            field=models.BigIntegerField(default=5),
        ),
    ]
