# Generated by Django 5.0.7 on 2024-09-21 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0011_alter_coredataprocessing_user'),
    ]

    operations = [
    ]
