# Generated by Django 5.0.7 on 2024-09-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0013_alter_coredataprocessing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coredataprocessing',
            name='max_rows',
            field=models.IntegerField(default=0),
        ),
    ]
