# Generated by Django 5.0.7 on 2024-10-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0014_coredataprocessing_max_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='coredataprocessing',
            name='learned_kanji_counter',
            field=models.IntegerField(default=0),
        ),
    ]
